### ISSUE TITLE
No module named version - missing file?

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#111]
https://github.com/equinor/fmu-dataio/blob/a443c46b1014c2e31b11105b75610dd0fd82507b/src/fmu/dataio/dataio.py#L43

From live example:

```
Traceback (most recent call last):
    [...]
    from fmu.dataio import ExportData
  File "/......./fmu-dataio/src/fmu/dataio/__init__.py", line 6, in <module>
    from fmu.dataio.dataio import ExportData  # noqa  # type: ignore
  File "/......./fmu-dataio/src/fmu/dataio/dataio.py", line 43, in <module>
    from .version import version
ModuleNotFoundError: No module named 'fmu.dataio.version'
```

Only valid explanation I can find is that there is no `version.py` file, although I don't really believe in it given that tests run fine etc. Anyhow, it's causing issues for some reason. This was introduced together with the deprecation of the `.to_file()` method in #106

**Comment by jcrivenaes** [comment]
I think this must have another explanation. The `version.py` file is created by the `setuptools_scm` package automatically when running `pip install -e .` og `python setup.py develop`. This file (`version.py`) is not under version control; hence it is added in `.gitignore`.

**Comment by jcrivenaes** [comment]
Can we close this @perolavsvendsen ?

**Comment by perolavsvendsen** [comment]
I am closing it for now with the likely explanation that this is caused by using fmu-dataio in non-installed state for dev purposes.
