### ISSUE TITLE
Default paths to global config

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/fmu-dataio#115]
Suggestion for missing config key in ExportData():

`config=None`

1. Look for ENV variable `FMU_GLOBAL_CONFIG` (should be an absolute path) which point to the YAML file
2. Look for relative paths `../../fmuconfig/output/global_variables.yml` (if inside RMS) or `fmuconfig/output/global_variables.yml` (in general) 
3. Raise an exception if nothing is found in (1) or (2)

**Comment by perolavsvendsen** [comment]
Think this is a duplicate. #141 #142
