### ISSUE TITLE
Include JSON Schema in integration tests

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#126]
Test outgoing metadata from tests against JSON schema to ensure consistency between schema and code. Currently integration is not tested until metadata hits Sumo validation point.

**Comment by perolavsvendsen** [comment]
Suggestion for test is to produce full metadata output, then confirm that it validates against the right schema.

**Comment by perolavsvendsen** [comment]
To be considered in #263 as well

**Comment by mferrera** [comment]
This may not be necessary to do when validation is built-into exporting. Do you think with that task in mind, this issue could be closed?

**Comment by perolavsvendsen** [comment]
Yes, assumptions are probably different now compared to back then. Would it be useful to generate the (JSON) schema during integration tests and validate against it as a "round trip" almost? I.e. emulate reality where `fmu-dataio` produces data, which are then validated against the schema upon storage into Sumo?
