### ISSUE TITLE
Support case-wide data (input)

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#136]
As a general rule, input data shall be handled elsewhere. However there may also be a need for handling input data within FMU workflows. An example of this is seismic observations.

The use case is to produce metadata for data that is currently being copied into share/ on case level, and used in each realization (via symlinks usually).

Currently, the `fmu` block has the following fields:
```
fmu:
  case
  model
  workflow
  iteration
  realization/aggregation  # realization if realization, aggregation if aggregation
```

Propose to add a third option to `realization`/`aggregation`:
```
fmu:
  case
  model
  workflow
  iteration
  realization/aggregation/XX
```
... to cover those instances of data which are not realizations nor aggregations.

Suggestions for naming:
`input` (too narrow?)
`observation` (too narrow, and already covered by the `data.is_observation`?)
`shared` (too confusing?)

Specific example: A seismic cube representing observed seismic used for this particular case.
(could also be relevant for other types of general observations pertaining to a case in the future)

**Comment by perolavsvendsen** [comment]
Perhaps what has been suggested offline: Will it be sufficient to simply *not* include those which are not applicable, e.g `iteration` or `realization`? I.e implicitly, if `realization` is missing, the data does not belong to a realization.

**Comment by perolavsvendsen** [comment]
Offline discussions @jsorb @jcrivenaes @ashildskalnes

Agreed to allow for `input`, as data objects on the same pattern as results. Agree to start with case level input data on same pattern as `aggregation`.
- [ ] Allow for `input` in fmu.dataio
- [ ] Implement and test on Drogon

**Comment by perolavsvendsen** [comment]
More offline discussions: Given the (temporary) support for generating metadata on `input`, it is considered a much better option to create completely separate schema for input data and not mix it into "results". This creates other problems and challenges, which will not be elaborated on here, related to automation.

**Comment by ashildskalnes** [comment]
OK with me:-)

**Comment by perolavsvendsen** [comment]
Clarification: Not talking about `input` - but `post-processed` data.

**Comment by perolavsvendsen** [comment]
A function must take existing data, with metadata, belonging to the _template_ - add _case_-metadata and store in right place on /scratch. End result shall be that pre-processed, case-wide data, is stored on /scratch with sufficient metadata to 1) be identified uniquely and 2) validate against schema for upload.

For the Webviz4D use case:
- Seismic attribute maps, currently created by a workflow in RMS. Made to be identical in layout/input parameters to synthetic maps produced during FMU realizations for later comparison.

- [ ] Create example of script handling pre-processed data in the case context. To replace current raw copy from /share/observation.

Consider separate schema for this type of data at a later stage (technically not "fmu-results")

**Comment by perolavsvendsen** [comment]
Support for this is now present in fmu-dataio, may consider closing this

**Comment by ashildskalnes** [comment]
Agree, but maybe create a new issue (if not existing) related to that (SUMO) aggregated surfaces currently gets case="realization"?
