### ISSUE TITLE
Schema documentation

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#166]
The metadata definitions should be documented, preferably in an automated fashion. This seems to be non-trivial. Current solution is to document through examples and through the JSON schema itself. But this is not super-accessible. A possible solution would be to turn the schema into markdown table.

Needs discussion

Key question is perhaps "How do you best document a denormalized data model represented by JSON schema?"

**Comment by perolavsvendsen** [comment]
First iteration merged in #193 

Still require more to be automated!

**Comment by perolavsvendsen** [comment]
Perhaps this is best solved by separating the schema/data model documentation from the fmu-dataio Python plugin documentation fully (just reference between them)?

- [ ] Build schema docs automatically
- [ ] Remove existing hard-coded schema docs from fmu-dataio main docs

**Comment by perolavsvendsen** [comment]
Partial solution to this removed in #409. Migration to Pydantic-based data model change the assumptions of this task. Automated documentation of the Pydantic model being tested in relations to #428

**Comment by mferrera** [comment]
I think that we can close this in favor of more specific tasks tailored toward improving the existing documentation. What do you think @perolavsvendsen ?

**Comment by mferrera** [comment]
Closing this in lieu of Pydantic autodoc and some issues with more specificity about how they can be enhanced. But the core of the issue is complete -- there is automated schema documentation generated, we just want it to be better
