### ISSUE TITLE
schema versioning

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#178]
Need to find a better way to handle schema versioning.

We need to retain multiple versions for legacy, and for building the schema endpoint. Note that URL reference is present in every single data object. Hence, incrementing the schema version is tricky.

A Git-challenge is that when a new increment is made, it has to be copied from the previous, hence the entire schema will look like a change - very effectively masking the actual change. Possibly there are some smart workarounds for this.

Possible to build the Radix endpoint directly from pre-defined releases of fmu-dataio?

**Comment by perolavsvendsen** [comment]
- [ ] Agree on deprecation warnings for outgoing schemas

**Comment by mferrera** [comment]
Closing this particular issue as a duplicate in favor for more recent issues in this repository, in fmu-results workshop.
