### ISSUE TITLE
data.time as explicit fields, not list

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#195]
Currently, the `data.time` field holds a list of `time` items.
Consider creating explicit time stamps? 

E.g. 
```
data.time: {
  time1: {
    time: <datetime>,
    label: MyLabel
    },
  time2: {
    ...

```

?

Question comes up in relations to Elastic querying and use in Webviz.

**Comment by perolavsvendsen** [comment]
Some discussion in #101 but not related to the list vs explicit fields

**Comment by jcrivenaes** [comment]
A proposal in the new refaktorization ongoing is (JSON version):

```
"data": {
    "t0": {
      "value": "1999-02-04T00:00:00",
      "label"; "base",
    },
    "t1": {
      "value": "2030-02-01T00:00:00",
      "label": "monitor"
    },
```

**Comment by perolavsvendsen** [comment]
Perhaps should be data.**time**.t0 etc?

**Comment by perolavsvendsen** [comment]
Bumbing this following ongoing offline discussions on this topic. Use the generic `data.time.t0`-style sequence for everything, or be explicit, e.g. `data.time.base` and `data.time.monitor` for 4D-specific stuff? Pros and cons, I guess.

**Comment by perolavsvendsen** [comment]
Summary of discussions on Slack.
- We will move on with `data.time.t0` and `data.time.t1` where each is a dictionary containing `label` and `value`.
- fmu-dataio will sort under the hood to make them chronological

https://equinor.slack.com/archives/C0152LS9TTP/p1674130438783349

**Comment by perolavsvendsen** [comment]
- [ ] Update examples
- [ ] Update schema
