### ISSUE TITLE
Parsing of "content"

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/fmu-dataio#20]
Must develop the parsing of content further so it fulfills various examples found in fmu-metadata definitions:

- [ ] `field_outline: {contact: owc}`
- [ ] `fluid_contact: {contact: owc}`
- [ ] `seismic: {attribute: xx, zrange: 2, filter_size: 1.0, scaling_factor: 3, is_timelapse: True, acquision_start_date: 2021-11-01, acquision_end_date: 2021-12-03, acquision_reference_date: 2021-11-20, offset: 0-15}`

**Comment by perolavsvendsen** [comment]
#43

**Comment by jcrivenaes** [comment]
I will think for `fluid_contact`, the `contact` subkey shall be required. For `field_outline`, I cannot see arguments why `contact` shall be required.

**Comment by perolavsvendsen** [comment]
> I will think for `fluid_contact`, the `contact` subkey shall be required. For `field_outline`, I cannot see arguments why `contact` shall be required.

Some clients (e.g. REP) will color the field outline differently depending on which type of fluid (contact) it is based on (oil or gas).

**Comment by perolavsvendsen** [comment]
Some content types noted when installing a live example:

- volume_regions (polygons)
- isochore_uncertainty_regions (polygons)
- pinchout (polygons)
- subcrop (polygons)
- wellpicks (table or possibly points?)
- fault_planes (points)
- pi (productivity index) (table)

There are also quite a lot of 4D seismic contents
