### ISSUE TITLE
Possibility to skip metadata file by setting config=False, or if config is missing required keys.

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/fmu-dataio#253]
It seems to be a use case, at least initially in "pre-sumo" settings, to use dataio to produce the files but avoid need for the SUMO valid metadata files, I.e. also avoid the need to set up the new metadata keys (`access`, etc) in `global_variables`.

One proposal is the let the `config` key be `False` in such cases.

Another proposal is that config is set pointing to global_variables as before, but required keys access, etc are missing. Now this will produce an error. Instead, it should give a UserWarning, and continue but without producing a metadata file.

**Comment by perolavsvendsen** [comment]
I think this is coming back to bite us now. Allowing non-valid input arguments, non-valid config etc etc is creating quite a large overhead in the code and increasing complexity significantly.

This is also tangled into the pattern where the config is changed during runtime. (Input from config and input from arguments are blended together, so we don't know if the wrong value came from argument (should not work, and should raise) or from the config (should not work, but not raise)).

It is further complicated by allowing input arguments in both the initialization of `ExportData` _and_ in the call to `ExportData.create_metadata()`

As I understand the requirement:
`fmu-dataio` should work even if the config is not valid. If key fields config fields are missing, then should still work. However, if key fields are _present_ and has wrong value, then fmu-dataio should raise.

Example: If a model setup does not have the field "access" in their global config, `fmu-dataio` cannot produce valid metadata - but it should still export the file with the right filename.

Example: If a model setup does have the field "access" in their global config, but the value is `True` (wrong), `fmu-dataio` should fail.

**Comment by tnatt** [comment]
Closing this as the initial issue problem was solved in #269. More work will be done here when starting on #602
