### ISSUE TITLE
Restructure schema to improve error messages

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#273]
The handling of `class == case` and `class != case` in the same schema creates confusing error messages. In short, the schema instructions are now to use a OneOf logic on two separate schemas: First check validity for the schema associated with `class == case`, and if that fails then validate against the requirements valid when `class != case`. When something in the latter does not validate, e.g. one of the attributes have the wrong format, the error message will then revert to the most basic error - which in JSON schema logic is that `class is not equal to "case"` - which is meaningless.

There are sometimes more nested error messages that can give a clue, but it is usually very tricky to debug.

Perhaps there are better ways of doing this. One option could be to use `if/else` logic, or possibly the `dependencies` keyword could help.

**Comment by perolavsvendsen** [comment]
Also consider to remove redundant (?) allowed "null" values for various fields. Are they needed?

**Comment by perolavsvendsen** [comment]
[Refinement 11.09.2023]

- This will not impact the actual production of metadata
- Makes more sense to use `0.9.0` rather than overwriting `0.8.0`, test it in `dev`.

- [ ] Move to `0.9.0`, not overwrite `0.8.0`
- [ ] Synch with latest changes in `0.8.0`

For a while, use both on the schema endpoint.

- [ ] Extract (enough) random documents from Sumo and verify that they validate on both `0.8.0` and `0.9.0´
- [ ] When happy, change fmu-dataio to `0.9.0`
- [ ] Consider which version to build the documentation on.

**Comment by adnejacobsen** [comment]
Can we close this? Since fmu-dataio is being "rewritten" and schema generation will be automatic?

**Comment by janbjorge** [comment]
> Can we close this? Since fmu-dataio is being "rewritten" and schema generation will be automatic?

From my point of view it depends on a few factors;
- Schema correctness
- Validator producing human readable error messages
- If the data is ill formed, will parsers give decent errors?

IMO; The generation of the schema will deal with part one of the factors above.

**Comment by mferrera** [comment]
Closing this now that we have Pydantic doing validation and providing error messages when that validation fails.
