### ISSUE TITLE
Add seismic.property

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#289]
Add attribute "property" under the conditional "seismic" attribute. 

https://github.com/equinor/fmu-dataio/blob/main/schema/definitions/0.8.0/schema/fmu_results.json#L550

@ezaezaeza

**Comment by jcrivenaes** [comment]
I propose we keep `attribute` as is and rather add `calculation` to descibe what calculation/operation

**Comment by ezaezaeza** [comment]
I think that will work fine. It will solve the issue with separating data and method
