### ISSUE TITLE
restart_from should be on iteration level

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#307]
An `iteration` is restarted from another iteration, so should move this from `case` to `iteration`.

Ref offline discussions FMU/Sumo/Webviz 2023-02-08

@alifbe @sago64

**Comment by perolavsvendsen** [comment]
Started a draft, but there are challenges. Moving the _definition_ is trivial. However, actually _populating_ this field is not trivial - perhaps not possible without serious refactoring, and perhaps not even then.

Currently, input arguments are given either at the creation of case metadata, or upon export of each individual file. We cannot give `restart_from` as input to creation of case metadata, because it is on iteration level. However, we cannot give the argument on every export of every file. We currently have no metadata information about the _iteration_.

I cannot immediately see any feasible ways of doing this even remotely user friendly.

**Comment by perolavsvendsen** [comment]
@jcrivenaes thoughts?

**Comment by alifbe** [comment]
We discussed a bit about this today and one idea is to store the uuid in scratch disk which will be picked up when generating iteration+object metadata

**Comment by perolavsvendsen** [comment]
Since it's the iteration that is restarted, not the case, it cannot be stored on case level. We have currently no storage on iteration level and we really should not create more situations where a process inside a realization must fetch data from outside itself.

It will possibly be fine if a restarted iteration is the only one in the case (then we could pass it to create_case_metadata and further into the case metadata), but that will not solve your original problem of having e.g "pred" next to "iter-x" within the same case. Then it would be the _case_ that is restarted, not the iteration. 

Alternatively, we would need to dump this into every realization in a restarted iteration for dataio to read. It's _possible_ but I also think it would create more problems than it solves. I also don't see what mechanism we have available for doing this which will be feasible for an end user to actually operate.

**Comment by alifbe** [comment]
How about we store it in case metadata. Something like:


fmu:
  model:
  case:
  restart_from:
    pred_ref: xdfdkfdejfjdjdffg

Of course the restart_from object will not be merged to final metadata

**Comment by perolavsvendsen** [comment]
Lets have a discussion on this. An issue is that we don't have a good way of recording the restart_from right now, and I am not immediately comfortable with assuming that the end user should manually put this into the case metadata in the middle of a run. So it would have to be some other type of configuration. I think we could merge the metadata change, and then have a proper discussion/refinement (involving ERT!) on how to best get the `uuid` into somewhere fmu-dataio can easily find it, and in a way that doesn't cause problems for others.

In the meantime, we can also experiment a bit with it to get some facts, of course.

**Comment by sago64** [comment]
![image](https://user-images.githubusercontent.com/55280570/217806280-1508d59b-2498-4ea9-94ca-1b1f490c21c1.png)
And then called in Eclipse DATA file: 
![image](https://user-images.githubusercontent.com/55280570/217806358-78dc85f5-1fec-4ee1-883f-585d0fb092c1.png)

**Comment by perolavsvendsen** [comment]
OK so the _need_ here is to communicate to dataio that "the iteration we are currently in is a restart from xxx" so that dataio puts it into metadata for each data object in that realization.

Technically, we don't need the information in the case metadata (we have it in each object) but we need somewhere to communicate it to dataio - could be that the only feasible place (currently) is in the case metadata but it feels very wobbly and confusing. Ideally, end users should never open this file and in future they may not be able to. So I think it's a bad design to rest on this file being edited. 

But this links to a topic we have discussed before: We need a sustainable channel of information from ERT to dataio. Today it would be a file, in future it could be an API. But then we need to keep end users away from it - if not we can never change. It needs to be an internal system file only. 

Lets call it e.g. "_info.json". If ERT dumped this file to RUNPATH in every realization, we could request new information to be included as needed. Perhaps start with RESTART_FROM. So it would be a keyword which is only transferred to _info.json. Other internal data that we would like to include could be included as we go along.

This way, we can communicate between ERT and dataio without involving manual work by the user in most cases, and in some cases where ERT doesn't have the information (like restart) the user puts it into the ERT config. That way, we funnel the user into ERTs interface, not encouraging them to go around it.

@sondreso any thoughts on the feasibility of this?

**Comment by perolavsvendsen** [comment]
(to test the concept, it should be feasible to create a custom FORWARD_JOB that creates a file on RUNPATH which dataio picks up.)

**Comment by alifbe** [comment]
@perolavsvendsen I like this idea. This will a good place to put information about `Simulation Mode` as well

**Comment by perolavsvendsen** [comment]
OK, so then I propose:
1) Merge the change in the schema, putting `restart_from` into `iteration`, not `case`
2) Initiate a discussion with ERT and look at the possibilities of establishing an information channel. First use case: Transfer a string from keyword `RESTART_FROM` in ert config to this channel.
3) Build functionality in fmu-dataio:_FmuProvider to fetch known data from this established channel, starting with `restart_from` and putting that into outgoing metadata.

**Comment by perolavsvendsen** [comment]
Existing ERT feature request: https://github.com/equinor/ert/issues/2359

**Comment by perolavsvendsen** [comment]
✅ Called for meeting

**Comment by alifbe** [comment]
Following up the meeting with ERT, I think we should just store RESTART_FROM information into environment variable and fetch it in fmu_provider.

Currently,  I have the code in fmu_provider where it fetch from _info.json and can easily modified it to fetch from RESTART_FROM environment variable. I'll create a PR on that tomorrow

**Comment by perolavsvendsen** [comment]
Until ERT actually populates (which could take a while given discussion today) such a variable, user must then set it explicitly through ERT config? What is the footprint of that today - is it feasible for end users to do?

**Comment by alifbe** [comment]
It should feasible for end user. In previous implementation (using _info.json) user only need to specify the runpath of iter-3. But I’m not sure how it will work with environment variable.
________________________________

**Comment by perolavsvendsen** [comment]
What is the value going to be used for further? The metadata entry is defined as the iteration.uuid of the source/parent iteration and must be a valid uuid4.

fmu-dataio can generate the uuid if it knows the case + iteration.name (hash of case.uuid + iteration.name). This requires fmu-dataio to parse case metadata get the case.uuid + get the iteration.name from the source.

So perhaps the path to the source is OK. If so, the environment variable ideally should be called "restart_from_path" or similar. Or it should support more than just a single string. We probably want to pass the actual uuid in the future.

**Comment by alifbe** [comment]
Yes. From the restart_from_path, fmu_provider will be able to calculate uuid (assuming the same "trick" to parse iteration name from the path is valid)

It works very well with the forward model like you suggested before. I got the correct restart_from uuid for both restarting from same case and restarting from another case. But that is because the realization-<IENS>/iter-<ITER> is expanded with the correct value for each forward model. But I'm not sure if that's the case with environment variable. I'll investigate more tomorrow.

**Comment by alifbe** [comment]
Close by PR #314
