### ISSUE TITLE
Clean-up related to restart_from

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#316]
We should probably address this in another PR? I think there are more changes that need to be done regarding moving `restart_from` from `case`  to `iteration` 
- Data model documentation
- dataio.py (InitializeCase class definition)
- create_case_metadata.py
- test_initialize_case.py

_Originally posted by @alifbe in https://github.com/equinor/fmu-dataio/pull/314#issuecomment-1438027307_

**Comment by alifbe** [comment]
Close using #325
