### ISSUE TITLE
Warnings do not show inside RMS

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#327]
When triggering `warn()` from inside RMS, it does not show.

Possibly relevant: #66 

Wanted behavior: Warnings show up in `stdout` also inside RMS.

**Comment by jcrivenaes** [comment]
This may be connected to implit warningsfilter in RMS. Whene I set warningsfilter to "always", warninsg are seen:

![image](https://user-images.githubusercontent.com/16700455/225893607-923593ef-fe10-4a76-b4bc-97a9edebde83.png)

**Comment by mferrera** [comment]
Closing as this is an issue we want to tackle in a more general manner between runrms + Ert.
