### ISSUE TITLE
Stop including parameters.txt contents, add support for .txt files

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#345]
Related: https://github.com/equinor/fmu-sumo/issues/186

Rather than including contents of `parameters.txt` into outgoing metadata, we want to explicitly upload this file as a data object. The role of fmu-dataio will still be to produce metadata.

- [x] Deprecate current export of parameters.txt contents into metadata for other files
- [ ] Support .txt data type and "parameters" content. _Is a more specific content needed?_

**Comment by daniel-sol** [comment]
This is well discussed within the sudo team, so don't disagree there. But I do think it is a better idea to upload the file as a json or yaml file. This ensures that not every user of results will have to make a parser for the text file.

**Comment by tnatt** [comment]
Closing this one as the initial issue is mostly solved. Only  "Support .txt data type" remaining, but that should be covered by issue #830
