### ISSUE TITLE
Enable writing of json files

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-dataio#354]
There are several datatypes in the fmu domain that as a data structure best fits in as a dictionary. 
The first types that spring to mind:

- parameter.txt
- observations
- alias lists (Although there has been discussed that these rather belongs as metadata for the case)

**Comment by perolavsvendsen** [comment]
Is the data class "dictionary"? Or "keyvalues"? Or "json"? I'm thinking of consistency with existing classes, e.g. `table`, `surface`, `cpgrid` etc.

To clarify, we will end up with is something like this:
`myfile.yml`
`.myfile.yml.yml`

**Comment by daniel-sol** [comment]
I have suggested to have class as dictionary. See PR #355

**Comment by perolavsvendsen** [comment]
I am wobbling a bit but I think I am leaning more towards using `json` (or `yaml`) as class, not `dict`. I worry about confusion with the `dict` data type in Python. A Python `dict` can contain "anything", but in this case we are constrained by what can actually be represented as json.

**Comment by daniel-sol** [comment]
Well, I beg to differ. I don't think json or yaml, or yml for that matter are the right terms. These are formats, not data structures. But I have changed the classname to dictionary to keep it distinct from pythons dict.

**Comment by mferrera** [comment]
This is implemented, but also superseded by #830
