### ISSUE TITLE
Confusing pattern for handling access from config vs arguments

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#363]
The `access` block (which is currently also being refactored a bit, see #295) is populated from the following sources, according to priority:

1. Input arguments to ExportData()
2. From pre-processed metadata
3. From config
4. From defaults

However, the current pattern is that `config` is read, then it is updated if `access_ssdl` is given as an argument: https://github.com/equinor/fmu-dataio/blob/517c71d9bdcf12c0f60bc6ee22169f8a86ef580a/src/fmu/dataio/dataio.py#L669

Hence, from this point, it is not possible to know if the input came as an argument (highest priority) or from the config (lower priority). When handling pre-processed data, this makes it difficult.

Suggest to refactor this so that we keep an understanding of the source of the access block throughout the code.

**Comment by jcrivenaes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fiks relatert til access](https://trello.com/c/42QRZTXC/1-fiks-relatert-til-access)

**Comment by mferrera** [comment]
Considering this solved by #628 and the discussions that developed around access control and the changes that have occurred to it.
