### ISSUE TITLE
Promote schema to prod

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#385]
Possible issue; current schema in `prod` is old.
- Promote current?

**Comment by equinor-ruaj** [comment]
refinement 27.11.2023:

before promoting to prod

- [x] test without setting `content` -> should be defaulted to `unset` and fail Sumo upload
- [ ] configure Sumo Test to use the updated schema and test

**Comment by perolavsvendsen** [comment]
Time to promote this now?
