### ISSUE TITLE
facies_thickness missing from allowed contents

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#464]
Not sure why, or if it was actually never there, but `facies_thickness` is a common output from FMU models and should be allowed as a content.

**Comment by janbjorge** [comment]
What fields should it contain?

**Comment by perolavsvendsen** [comment]
No fields, just allowed as value for `data.content`

**Comment by janbjorge** [comment]
But, every data.content is connected to a data-structure now, ex. data.content = depth, must have the field depth_reference.

**Comment by perolavsvendsen** [comment]
Added to [this list](https://github.com/equinor/fmu-dataio/blob/018c7c728d487caaefef4bc8ab13c41139f5e6e3/schema/definitions/0.8.0/schema/fmu_results.json#L281), similar to e.g. "thickness". But not with an additional conditional field.
