### ISSUE TITLE
Consider renaming `fmu.dataio.scripts` to `fmu.dataio.workflows`

### ISSUE THREAD

**Issue by mferrera** [equinor/fmu-dataio#480]
`scripts` is a rather broad term when in fact what it contains are workflows -- though just the one workflow at the moment.

**Comment by perolavsvendsen** [comment]
It's technically a script, which has been decorated as an ERT workflow _job_. The actual workflow is locally defined. (It calls this workflow job, which in turn calls the script.)

I don't know the consequences of renaming it - but I am unsure if `workflows` is the right word. This is also probably where we would put other scripts, which could be decorated as an ERT FORWARD_MODEL JOB. Or just plain CLI scripts, if that becomes a need.

**Comment by mferrera** [comment]
Will this script ever be called outside of a workflow context? I just find it a bit odd to see a scripts subpackage within a package. Typically a directory named scripts in a package contains tooling to working with that package (i.e. building it, generating test data, etc).

**Comment by perolavsvendsen** [comment]
I don't think this particular script will be called outside the workflow context. Or, technically, outside the context of a workflow _job_, which in turn is not called outside workflow context. But then we are also being very ERT specific. As in, the term workflow specifically points to an ERT workflow (job).

I can't find an obvious "standard" way of doing this in other relevant packages.
