### ISSUE TITLE
Improve metadata for `parent` information

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/fmu-dataio#537]
Related to this: #278, #299

Currently, it is possible to give a `parent` for a grid property. However this only comes in the file name, not in the metadata themselves.

- Fix so parent becomes in the data metadata

In addition, a `parent`  may be useful for other data types:

- Seismic cubes, where the parent is the name of the original seismic cube
- Surfaces?

However, in these cases, having `parent` as the part of the file name is not always a wanted feature 

- [ ] Consider having the possibility to turn on/off parent as part of the file name

**Comment by mferrera** [comment]
I think we can close this with #677 merged
