### ISSUE TITLE
Discontinue legacy schema

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#571]
Current, both old and new schemas are in `prod`. Should discontinue the old.

- [x] Deploy version of `fmu-dataio` that uses Pydantic
  - [x] Komodo
  - [x] RMS

When all workflows (?) are producing "new" metadata, discontinue old schema.

- [x] Sumo OK
- [x] fmu-dataio OK

- [ ] Discontinue and remove legacy schema

**Comment by mferrera** [comment]
Dependencies we plan to tidy up before returning to a regular release schedule and discontinuing the legacy schema:

- [ ] All providers return Pydantic models
  - [ ] #572 
  - [ ] #564
  - [ ] #565
  - [ ] ...
- [ ] Optional: #573
- [ ] #492

After these issues are cleaned up we will begin testing on real models. It may also be a good time to start adding more integration tests.
