### ISSUE TITLE
Improve how we signal "preprocessed"

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#593]
Ref discussion 10/4-2024, @tnatt @HansKallekleiv @jcrivenaes 

_Pre-processed data in this context are data generated typically directly in RMS, then picked up by e.g. ERT PRESIM workflows when launching FMU workflow. They are exported with partial metadata, tagged with a dedicated `_preprocessed` tag to flag that these are "partial"._

Currently, "preprocessed" is given as argument to the ExportData class init, i.e.:
```python
exp = ExportData(context="preprocessed")
```

### Option: Create separate class for preprocessed data
Given the pattern of class names `ExportData`, `ExportAggregatedData`, consider to introduce `ExportPreprocessedData`

```python
exp = ExportPreprocessedData(...)
```

### Option: Create separate argument for preprocessed
```python
exp = ExportData(preprocessed=True)
```

**Comment by tnatt** [comment]
Leaning towards this:
```python
exp = ExportData(preprocessed=True)
```
I think this would be the easiest from a user perspective, and easiest to implement. Any objections to it? If not, I have a PR coming up to deprecate the `fmu_context="preprocessed"` and add it as an argument instead 🙂

**Comment by perolavsvendsen** [comment]
Without having looked into the details or anything: This means that `ExportData` will continue to handle different contexts. The alternative option would be to have different classes for different contexts, like we already have started somewhat with the `ExportAggregatedData`.

If not, we should probably also look into removing the `AggregatedData` class and make `ExportData` handle that as well? (May not be a very big operation, the usage of this class is very limited - probably only used in one service associated with Sumo.)

So converge on a single class, or split into separate classes per context (which would probably all inherit most of their logic from some common `super`)
