### ISSUE TITLE
Abstract away common `fmu-dataio` use cases

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/fmu-dataio#668]
**Based on discussion between fmu-dataio + webviz May 29th:**
---

**Today:**
Currently the examples for different data types in `fmu-dataio` consist of different semi-long scripts (e.g. https://fmu-dataio.readthedocs.io/en/latest/examples.html#exporting-fault-polygons). Maintaining these centrally will not be possible if modelling projects copy them from the docs.

**First improvement step:**
To both make it easier for users, and to improve/maintain common data exports centrally, these should be abstracted away to ~one-liner which can be called in RMS, and expose as few arguments as possible to the user (we can later add new arguments with default values if needed).

**Second improvement step:**
Experiment with simple RMS plugins to give a simple GUI to user in order to fill in values for the high-level functions from step one. This would require distribution system internally for RMS plugins.

**Comment by perolavsvendsen** [comment]
Yes, this is good. It increases robustness and sustainability (centrally vs locally maintained), it reduces the amount of locally implemented code and it will dramatically improve/ease updates and changes, I assume.

I think this could/should be seen in relations to the discussions around more "product" thinking around FMU results. If/when possible, wrappers should be defined around which data is exported, not which data _type_ is exported. I.e. a wrapper for "inplace volumes", not for "tables" and then provide:

1. Definitions in the data model
2. Export function/wrapper
3. Documentation
4. Endpoint for consumption (from Sumo)

It's fine to focus on the fmu-dataio stuff first, but important to keep in mind that "getting the data into Sumo" is not an end state.
