### ISSUE TITLE
Specify if data object is 4D seismic

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#673]
Data model should support quick identification of data objects that are 4D seismic. E.g. separate 4D from 3D seismic.

## Related to/triggered by:
- [x] https://github.com/equinor/fmu-sumo/issues/324

## Options:

1. Split current data.content `seismic` into `seismic3D` and `seismic4D`
   - Breaking change
3. Add `data.seismic.dimensionality` (enum) with allowed values (`1`, `2`),`3` and `4` [🟢 preferred!]
   - If only applicable to seismic
4. Add `data.dimensionality` (enum) (optional) with allowed values as above.
   - If applicable to other data types also, e.g. surfaces
   - [ ] https://github.com/equinor/fmu-dataio/issues/369

**Comment by mferrera** [comment]
Closing this per discussion in https://github.com/equinor/fmu-sumo/issues/348 and offline discussion. Relevant commentary was that 4d seismic is not really a data type unto itself but an interpretation of more than one 3d data type.
