### ISSUE TITLE
`fmu.model.name` and `fmu.model.revision` optional or not?

### ISSUE THREAD

**Issue by tnatt** [equinor/fmu-dataio#684]
Align `meta.FMUModel` and `globalconfiguration.Model`

To be able to produce metadata we require `fmu.model.name` and `fmu.model.revision` to be set in the global config. But the scema version used to validate before sumo upload has these fields as optional.

https://github.com/equinor/fmu-dataio/blob/58a554f06663e1ced617dbc2ab86df79423ee573/src/fmu/dataio/datastructure/meta/meta.py#L157-L170

https://github.com/equinor/fmu-dataio/blob/58a554f06663e1ced617dbc2ab86df79423ee573/src/fmu/dataio/datastructure/configuration/global_configuration.py#L41-L48

**Comment by tnatt** [comment]
@perolavsvendsen do you think we can start setting `fmu.model.name` and `fmu.model.revision` as required in the schema? It should not affect any users that produces their metadata through dataio.
Of course there might exists some old preprocessed data somewhere without these fields... they will then get an error saying its missing and that they have to re-create the preprocessed data.

**Comment by perolavsvendsen** [comment]
Yes, definitely. I thought they were required already. There is a lot of dependencies on them. It would cause problems if (particularly case metadata) was produced _without_ these two.

Regarding pre-processed data - is `fmu.model` strictly necessary to have in pre-processed (stub) metadata at all? Or can we live with this being appended when running FMU (like `fmu.case` etc)?

**Comment by tnatt** [comment]
Nice! I will make the change 👍 
And forget about my comment regarding preprocessed data .. you are correct they will not be in there anyway and no error will be raised! It is only added when the `fmu` block is added upon re-export into scratch 😄
