### ISSUE TITLE
Consider using `summary` as content

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#689]
Nothing seems ideal here, but current `content` = "timeseries" seems more like a data type than a content. It also forces consumers who need `summary` explicitly (?) to put logic on `tagname`, which in turn forces user to "remember to put the correct string here". It smells a little bit.

https://github.com/equinor/fmu-dataio/blob/1838fa7374a4f89c2f65d597ec07d06bfc4424d3/src/fmu/dataio/datastructure/meta/enums.py#L40

Note that comment informs that this is _really_ summary:
https://github.com/equinor/fmu-dataio/blob/1838fa7374a4f89c2f65d597ec07d06bfc4424d3/src/fmu/dataio/_definitions.py#L75

Would it be an improvement to allow (and expect) `summary` as a content when data contains summary?

**Comment by mferrera** [comment]
Offline discussion has pointed this toward defining this content type as `simulationtimeseries`.

There was also discussion about whether a sub-category/sub-content for `timeseries` could be a relevant choice to make here. For the moment, having only one candidate for a sub-category, it make end up being an undesirable pattern if it's the only sub-category. Another possible mark against it being a sub-category is that `simulationtimeseries`, being a collection of timeseries vectors, may actually make it a super-type of `timeseries`.
