### ISSUE TITLE
Address test warnings regarding deprecated behavior

### ISSUE THREAD

**Issue by tnatt** [equinor/fmu-dataio#735]
With all the changes in dataio lately we are emitting a lot of warnings (~450) when running tests due to deprecated behavior. We should silence the warnings by modifying our tests to follow latest standards, or catch the warnings with pytest.warns

**Comment by mferrera** [comment]
Another option is to use mark tests that we expect to emit warnings, but do not want them displayed, with [filter warnings fixture](https://docs.pytest.org/en/6.2.x/warnings.html#pytest-mark-filterwarnings)
