### ISSUE TITLE
Promote dev schema to prod 

### ISSUE THREAD

**Issue by tnatt** [equinor/fmu-dataio#760]
Now that we have discontinued the legacy schema #757  we should promote the dev schema version to prod.

We should wait ~2 weeks to ensure that komodo includes the `fmu-dataio 2.2.1`

Once done 
- [x] Tell Sumo to change to schema `fmu_results.json` instead of `fmu_meta.json`
- [ ] Remove part of code that copies `fmu_results.json` to `fmu_meta.json` in the radix container
  https://github.com/equinor/fmu-dataio/blob/8981c102f02f6db0800f3861a6ec961a9ddfe344/schema/app/install-schema-files.sh#L35-L38

**Comment by mferrera** [comment]
Seems Sumo team did this promotion today.
