### ISSUE TITLE
Introduce Iteration and Realization class

### ISSUE THREAD

**Issue by equinor-ruaj** [equinor/fmu-dataio#774]
TLDR:
Sumo wants two new object classes `Iteration` and `Realization` to:
* Avoid duplication of `fmu.realization.parameters`
* Enable tagging reference realizations
* Enable sharing specific iterations
* Enable more granular retention

Realization objects would be similar to child objects, minus the `data` and `file` blocks.
Iteration objects would be similar to child objects, minus the `data`, `file` and `fmu.realization` blocks.

Later we can then remove the `fmu.realization.parameters` block from child objects.

Ref. Sumo issue: https://github.com/equinor/sumo/issues/153

**Comment by perolavsvendsen** [comment]
https://github.com/equinor/fmu-dataio/issues/345
