### ISSUE TITLE
ENH: Add reference flag to realization block

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#826]
Ref https://github.com/equinor/sumo/issues/153 and also https://github.com/equinor/fmu-dataio/issues/774

To solve the use case of tagging individual realizations as "reference", a reference flag of some kind is needed in the metadata structure. This would primarily be set by Sumo, so not during data production.

My suggestion is `fmu.realization.is_reference`.

Opinions?

**Comment by mferrera** [comment]
This seems reasonable to me. Is a default of `False` OK from the Sumo end?

**Comment by perolavsvendsen** [comment]
We confused ourselves severely, but we don't think it matters much from our side...

So for now we suggest that it is defaulted to `False`. Should also be included in the list of contractual metadata elements, as we would like to explicitly index this.

The idea is that it will be flipped to `True` by the user using the Sumo front-end or the through the API via scripts.

There is also a possible next step where this information is available when running the case itself, and that `fmu-dataio` sets it to `True` for one or more realizations. But for now, this is speculative.

**Comment by tnatt** [comment]
So for my understanding this `is_reference` should only go into the new `Realization` object metadata right? ref #785.
How would it work to add the `fmu.realization.is_reference` to the contractual list when the `fmu.realization.is_reference` is not present in the individual data objects metadata? will the indexing in Sumo still work fine?

**Comment by perolavsvendsen** [comment]
> So for my understanding this `is_reference` should only go into the new `Realization` object metadata right? ref #785. How would it work to add the `fmu.realization.is_reference` to the contractual list when the `fmu.realization.is_reference` is not present in the individual data objects metadata? will the indexing in Sumo still work fine?

Yes, adding it to the contractual list does not make it mandatory - it just means that it should not _change_ erratically. E.g. be changed from a string to an object (which would cause indexing problems). So it's only the definition of it which is "locked", not it's presence.

In this case, if we index it, we will simply assume a contract that states that `fmu.realization.is_reference` is a `bool` (or `null`) and will continue to be so (when it is present).
