### ISSUE TITLE
Support the pyarrow format

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#88]
fmu-dataio: Knowledge of the pa.Table format. Similar to current handling of pd.Dataframe.

## Wanted end-state ##
* In ERT perspective, one FORWARD_JOB that extracts SMRY-data, exports via fmu-dataio, uploads to Sumo.
* Starting point (from fmu-dataio perspective): pa.Table object
* fmu-dataio exports to disk "as usual".

## Tasks ##
* Implement support for pa.Table as known table object, with arrow as output.

## Requirements ##
* Minimize footprint in ERT workflow for end user. E.g. rather than one FORWARD_MODEL for each step (data out, metadata on, upload), consolidate as much as possible.
* fmu-dataio to be sourced in smry2arrow.py

## Schematic example ##
exp = ExportData()
exp.to_disk(pa.Table)

**Comment by berland** [comment]
WIP: https://github.com/equinor/ecl2df/pull/358

**Comment by perolavsvendsen** [comment]
#92
