### ISSUE TITLE
Able to run through ERT forward jobs

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#89]
Currently, fmu-dataio is sensitive to current working directory. It will not work when pwd is on realization root and/or config path or other known contexts when running with ERT.

These are the known contexts that must be supported:
* ERT forward job
* ERT workflow
* RMS job, within ERT forward job
* RMS job, non-FMU run

**Comment by anders-kiaer** [comment]
Do you have the PR or branch somewhere where you tried hacking your way through this use case @perolavsvendsen ? 🙂

**Comment by perolavsvendsen** [comment]
> Do you have the PR or branch somewhere where you tried hacking your way through this use case @perolavsvendsen ? 🙂

Yes, quick & dirty. More dirty than quick. https://github.com/perolavsvendsen/fmu-dataio/pull/7

Aside from readability etc, I have problems with the whole concept of venturing outside the realization folder for any reason. I don't think that's very future proof.

**Comment by perolavsvendsen** [comment]
Offline discussion points:
- Detect `jobs.json` (or any other diagnostic file, but jobs.json is already read) and use that as indicator for both `cwd` and `is_fmurun`

Assume that each realization is containerized and self-contained.

Make something that works, present problem to ERT team to find better solution.

**Comment by perolavsvendsen** [comment]
Possibly solved in #93

**Comment by perolavsvendsen** [comment]
Not solved in #93 
Files are exported to ../../share/results, also when running as FORWARD_JOB, which puts the results outside the realization.

**Comment by perolavsvendsen** [comment]
Drafting an anchor on `runpath` rather than `cwd` in #99

**Comment by perolavsvendsen** [comment]
@jcrivenaes this can be closed, no?
