### ISSUE TITLE
Inplace volumes: Create enums of columns names

### ISSUE THREAD

**Issue by tnatt** [equinor/fmu-dataio#920]
Right now there is a lot of strings flying around related to column names in the inplace_volumes module. This makes us vulnerable for typing errors e.g. `STOIIP` vs `STOOIP` 
We should make some enums instead.

https://github.com/equinor/fmu-dataio/blob/32cb40631244a0d9d0025962f5da7f4ff93c386c/src/fmu/dataio/export/rms/inplace_volumes.py#L28-L71

**Comment by mferrera** [comment]
Suggest that these be moved to a separate module, like `_definitions.py`. Then these can be used elsewhere, such as in the results schema, without the need to check and import roxar/rmsapi
